### ISSUE TITLE
Jump motion sort of 

### ISSUE THREAD

**Issue by lanceschi** [maximeh/leaflet.bouncemarker#23]
Hi,

I was wonder if it is possible to simulate a jump (alike) motion with this useful plugin?

Thanks,
Luca

**Comment by maximeh** [comment]
@lanceschi hey, any news ? I know it's been a while :)

**Comment by lanceschi** [comment]
@maximeh: sadly nothing worth to mention. I remember I ended up modifiying yours for that specific project. I made the pins jump three times. The result was satisfactory and close to [Leaflet.SmoothMarkerBouncing](https://github.com/hosuaby/Leaflet.SmoothMarkerBouncing)

I got back to leaflet.js map representation only recently for another project but this time no jumping pins. :smile: World trade data representation via choropleth map.

Cheers,
L

**Comment by maximeh** [comment]
@lanceschi No problem. I'll close this issue and if/when I find the time, I'll try to implement that. Could be fun :)
