### ISSUE TITLE
bouncemarker does not work in conjunction with leaflet's marker cluster

### ISSUE THREAD

**Issue by heaversm** [maximeh/leaflet.bouncemarker#27]
If using mapbox's [marker cluster plugin](https://github.com/Leaflet/Leaflet.markercluster), which applies a transform to map markers' translate property as well, bouncing a marker prevents any future marker cluster separation from happening on map zoom. I think you could solve this by making sure to always use translate3d, and perhaps reading or clearing any currently existing translate values.

**Comment by silentjay** [comment]
Would be good if we could get these two plugins working together

**Comment by maximeh** [comment]
I need to look into this. I don't have a lot of times to dedicate to this at the moment. If anyone has a patch, it's always more than welcome :)

**Comment by xEuPhoRiA-** [comment]
Yea I would love to see this working with markercluster as well

**Comment by maximeh** [comment]
I know it's been 2 years; sorry for that...
As I said in #32; making the two plugins compatible is going to be tricky. If anyone has ideas; I am open to suggestion and patches :)

**Comment by EzequielGv83** [comment]
I guess that it is easier to disable clustering on the bouncing marker or make your own clustering function so that it only clusterizes non-bouncing markers.
