### ISSUE TITLE
Add package.json so this plugin can be installed from npm

### ISSUE THREAD

**Issue by rhewitt22** [maximeh/leaflet.bouncemarker#28]

**Comment by jontroncoso** [comment]
:+1:

**Comment by gommo** [comment]
+1

**Comment by dawadam** [comment]
+1

**Comment by maximeh** [comment]
Hey,

I finally took some time to create this file, since I don't really use npm, I don't know if it's any good or really how to use it.

If you have any problems, please feel free to open a new issue.
