### ISSUE TITLE
Bouncemarker latitude change when removing/adding it multiple times

### ISSUE THREAD

**Issue by blankoworld** [maximeh/leaflet.bouncemarker#29]
Environment:
- leaflet map
- some overlay to regroup markers
- one marker should bounce
- options of my marker:

``` javascript
marker.options.bounceOnAdd = true;
marker.options.bounceOnAddOptions = {duration: 3000, height: 150};
marker.options.zIndexOffset = 10;
```

When I click on the checkbox to display the overlay: the bounce marker is OK.
Then I click again. The bounce marker disappears. Well.
Finally I click again on the checkbox. All markers appear. But the bounce one is displayed some pixel on the top from the location where it should appear.

I just display some information, and the latitude seems to change each time I add the marker on the map. Except the first time.

By deleting this line: https://github.com/maximeh/leaflet.bouncemarker/blob/master/bouncemarker.js#L173 all seems to be OK. The bouncer is displayed well. The latitude don't change. And I don't notice any problem.

So I'm curious: what the goal of this line 173?

Thanks in advance for all kind of information about that ;)

**Comment by blankoworld** [comment]
I try something: remove the marker during animation: the marker keep the LatLng from where it was removed. Which explain why the marker always go to the top of the map.

To my mind it would be better to add some other options on the marker to keep the original LatLng.
And then use it (if exists) as LatLng. If no one, use marker LatLng.

What do you think about that?

**Comment by maximeh** [comment]
Hi,

Sorry that it took almost a year for me to reach out to you, did you solve your problem ? If so how did you do it ?
Any patch is welcome :)

**Comment by blankoworld** [comment]
Thanks for the reply.

Since this problem I change the entire environment so that I'm not sure I can reproduce the problem and fix it if needed:

  * I delete django-leaflet from dependancies
  * I update to Leaflet 1.0.0
  * As I'm not comfortable with JS, I prefer to not use the bouncer than adding something that fail in some cases or that I need to patch

You're right, in the past I would make a pull request. But as JS was mysterious for me, I didn't want to break something I don't understand ;)

Do you want that I attempt to integrate the bouncer again and check if Leaflet 1.0.0 resolve the problem or if it's already here?

**Comment by maximeh** [comment]
If you have time to test it again, that'd be great ! I could from there to try and fix your issue.

**Comment by blankoworld** [comment]
So I try again. And make a video to show you the problem: http://dl.free.fr/e7zJrCPgu (if you have any other website on which I can upload the video, ask me).

First I refresh Firefox (Ctrl + R). We saw the bouncer that make a break, then teleport itself to the right position.
Then I display all other points. The bounce marker is displayed as it should be.
And I uncheck the filter. Check it again. We see that the bouncer is more on top. Then uncheck/check, the bouncer is more on top. Again and again. Each time I uncheck and check, the bouncer use more and more height.

The code I use to add bouncer is here: https://github.com/eost/gissmo/blob/master/gissmo/static/js/site_map.js#L405-L406

The initial solution I gave (delete line 173 in bouncermarker.js) doesn't work with my current project.

What's curious is that each time it takes exactly the same height to go on top. But I don't know how many pixels.

**Comment by aman-kumayu** [comment]
You can add offset to a point not marker as point works with pixels and markers works with coordinates, you have to use leaflet's inbuild functions for converting coordinates to marker and then vice-versa like this 

var latLong = L.latLng([0,0]),

var point = map.latLngToContainerPoint(latLong);

var newPoint = L.point([point.x - 10, point.y - 57]);

var newLatLong = map.containerPointToLatLng(newPoint);

**Comment by maximeh** [comment]
Hey,

I am happy to report that I finally have a fix on that. I will commit it soon. I just need a little bit more testing.

**Comment by maximeh** [comment]
Just to keep you guys up to date; I did more testing, there's still an issues if I bounce and zoom at the same times; it may happen  that the markers moves. I don't know why yet; but I plan to fix that before pushing my current changes.

**Comment by maximeh** [comment]
@blankoworld I just pushed a bunch of changes; I think it should be good now, could you give it a try and comment here ? Thanks a lot !
