### ISSUE TITLE
Can't install from Bower

### ISSUE THREAD

**Issue by pvillaverde** [maximeh/leaflet.bouncemarker#31]
Hey!

I'm not beeing able to install it from bower, neither form github url. 
I get ENOTFOUND Package leaflet.bouncemarker not found.
Could it be because in bower.json is leaflet-bouncemarker, with dash instead of dot?

Thanks in advance!

**Comment by maximeh** [comment]
Hey, 

Thanks a lot for reporting this. There's a few leaflet-bouncemaker packages in the bower registry which are not mine and don't exist anymore.
I need to properly register the package.

I have sent mails to the current owner of said packages so they can remove them and I can register mine.
I will keep this open until it's resolved.

Again, thank you for pointing it out.

**Comment by danalloway** [comment]
heya!

Glad to unregister that for you all, and apologies for creating any confusion.
Had to re-fork the project to unregister it, and for whatever reason the name was `leafelet-bouncemarker` in Bower (notice the extra `e` in there).
Anyway, it has been unregistered successfully, let me know if I can be of any further assistance!

Cheers everyone.

**Comment by danalloway** [comment]
oh, you know what!
I created the `bower.json` file in my fork back in 2015 (merged in this PR https://github.com/maximeh/leaflet.bouncemarker/pull/26) that must be how my GitHub account got on it... odd.

**Comment by maximeh** [comment]
@danalloway indeed I did not even notice that. Thanks a lot for your prompt response.

**Comment by maximeh** [comment]
@pvillaverde I just registered my repository in bower, so everything should be good. Let me know if you have any more trouble. I'll close this for the time being.

Thanks again !
