### ISSUE TITLE
Can't seem to get the bounce to loop

### ISSUE THREAD

**Issue by Zaknarfen** [maximeh/leaflet.bouncemarker#37]
Hi I followed all the instructions in the README and everything works fine, but for some reason, the loop flag set to -1 or 2, 3, etc... doesn't make any difference. The marker always bounces once. I am using the latest version of Leaflet. I also tried to add a callback and it's never called.

**Comment by maximeh** [comment]
Could you share your code? That would make it easier to see what's going on in any case.

**Comment by maximeh** [comment]
So I was trying quickly and it's working. I've noticed that the gh-pages branch is not using the latests bouncemarker.js but if you took the one from master, it's working fine on my end.
Curious to see your code, we can figure out what's the problem then

**Comment by Zaknarfen** [comment]
Ok, I am using Angular so this is the imports part:

![header](https://user-images.githubusercontent.com/4223973/113025158-feef1700-915d-11eb-9822-7721c21fd9de.jpg)

I am using the @skyraptor npm package that should match what you have here, I think he just removed the `bouncemarker` flag. [This](https://www.npmjs.com/package/@skyraptor/leaflet.bouncemarker) is the link to it.

This is the method itself, nothing special
![bounce](https://user-images.githubusercontent.com/4223973/113025404-4d041a80-915e-11eb-993d-f948d2d5c8ab.jpg)

What's puzzling me is that it bounces and it works but just once, and the callback won't work.

**Comment by maximeh** [comment]
It's indeed very confusing.. I've never used angular so I guess you'll have to do some debugging there. That looks fine to me.

**Comment by Zaknarfen** [comment]
I actually made a codesandbox project to test this and it also works there fine. You can see it [here](https://codesandbox.io/s/angular-bouncemarker-leaflet-6xo8z). I don't know why mine doesn't.

**Comment by maximeh** [comment]
That’s indeed very weird :/ I’m afraid I won’t be of a lot of help since it’s working in other context and I really know nothing of Angular.
That being said, I would really appreciate if you post your solution here for the next person if that happens again.

I had no idea there was forks for angular, I don’t know why theses are not merged back here though :/.

**Comment by Zaknarfen** [comment]
I don't know either. For anyone using Angular, all you gotta do is follow the setup in the codesandbox I posted. To use the library itself just install through npm, import as I showed above and use it normally.

**Comment by maximeh** [comment]
Heya,

I'm doing a little triage, I know it's very old. I've tried your sandbox again and... it seems to work fine. So I guess either it was a browser bug and something else that got fixed along the way.

So I'll be closing now, feel free to re open if you think there's still issues.
