### ISSUE TITLE
Demo link broken

### ISSUE THREAD

**Issue by DMcDona** [maximeh/leaflet.bouncemarker#38]
Just an FYI that the "Watch the demo." link under "Bouncemarker plugin for Leaflet" in readme returns a 404. 
Cheers!

**Comment by maximeh** [comment]
Ohh thank you so much! I had totally missed that! Lemme fix it right away.

**Comment by ulken** [comment]
@maximeh Not sure if it has anything to do with yesterday's release (can't imagine?), but the marker icon is now missing on the demo page.

**Comment by maximeh** [comment]
Forgot to reply there: It's a cross origin thing; basically it can't seem to work with https, if you look the link is explicitly http; so if your browser redirect you automatically, it won't work. 
I think it was becauses of the way github-pages are served from different domain names; maybe it has changed; I've honestly never had enough time to look into this.
