### ISSUE TITLE
`.bounce()` is missing in TypeScript definition

### ISSUE THREAD

**Issue by ulken** [maximeh/leaflet.bouncemarker#40]
It should be changed to something along the lines of:

```ts
import 'leaflet';

declare module 'leaflet' {

  export type BounceOptions = {
    duration: number;
    height: number;
    loop: number;
  };

  export interface MarkerOptions {
    bounceOnAdd?: boolean;
    bounceOnAddOptions?: BounceOptions;
    bounceOnAddCallback?: () => void;
  }

  export interface Marker {
    bounce(callback?: () => void);
    bounce(options: BounceOptions, callback?: () => void);
  }

}
```

Made some other changes in there as well, like replacing `Function` with `() => void`. According to https://www.typescriptlang.org/docs/handbook/2/functions.html#function:

>This is an untyped function call and is generally best avoided because of the unsafe any return type.
>
>If you need to accept an arbitrary function but don’t intend to call it, the type () => void is generally safer.

Also replaced `import * as L from 'leaflet'` with `import 'leaflet'` as `L` was never referenced.

**Comment by maximeh** [comment]
Don't you want to make a PR at that point? I don't the added value of me copy/pasting your changes is really high :)

**Comment by ulken** [comment]
Sure, just wanted to check in first. I'll get to it later today.

**Comment by ulken** [comment]
@maximeh https://github.com/maximeh/leaflet.bouncemarker/pull/41
